### ISSUE TITLE
Improvement(?) for TaPL/TaPL/Chapter7Dep.idr

### ISSUE THREAD

**Issue by googleson78** [andorp/TaPL#1]
I'm not sure if this is the right place to post this, and also if you don't already know about this, but decided against it, but

Instead of using e.g.
```idris
subst : {n : Nat} -> (e : Exp n) -> Fin n -> Exp (pred n) -> Exp (pred n)
```
and having to calculate a function (less type info, more matching), you could do
```idris
subst : {n : Nat} -> (e : Exp (suc n)) -> Fin (suc n) -> Exp n -> Exp n
```

Sorry if I'm already saying something you're aware of!

**Comment by andorp** [comment]
Applied in d6b61b52c0747078d57b1b581f66e8b50c22c6ab 
Thanks for the suggestion. I wondered if that was possible, but I was pretty tired when I pushed the last change.
